require 'just_giving/error'
require 'just_giving/response'
require 'just_giving/configuration'
require 'just_giving/simple_donation_integration'
require 'just_giving/api'
require 'just_giving/account'
require 'just_giving/charity'
require 'just_giving/event'
require 'just_giving/fundraising'
require 'just_giving/search'
require 'just_giving/donation'
require 'just_giving/railtie' if defined?(Rails) && Rails::VERSION::MAJOR >= 3